behaviors:
  MazeAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0005
      beta: 0.03
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 5
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      memory:
        sequence_length: 32
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
